import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  aiwithjavaSidebar: [
    // If you only have intro.md for now, this is enough:
    'intro',
    // Later you can switch to autogenerated:
    // { type: 'autogenerated', dirName: '.' },
  ],
};

export default sidebars;
