import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  resourcesSidebar: [
    { type: 'autogenerated', dirName: '.' },
  ],
};

export default sidebars;

